### ISSUE TITLE
ImportError: torch_points_kernels/points_cpu.so: undefined symbol: _ZNK2at6Tensor4normEN3c108optionalINS1_6ScalarEEENS1_8ArrayRefIlEEb

### ISSUE THREAD

**Issue by dpxudong** [torch-points3d/torch-points-kernels#85]

**Comment by ptoews** [comment]
I have the same issue with version 0.6.10, in version 0.7.0 it disappears.

**Comment by dipesh-commits** [comment]
Previously, it was throwing the same error as above. After successfully building using v0.7.0, it throws the following error:

>>> import torch_points_kernels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Desktop/dev/torch-points-kernels-0.7.0/torch_points_kernels/__init__.py", line 1, in <module>
    from .torchpoints import *
  File "/home/Desktop/dev/torch-points-kernels-0.7.0/torch_points_kernels/torchpoints.py", line 7, in <module>
    import torch_points_kernels.points_cpu as tpcpu
ModuleNotFoundError: No module named 'torch_points_kernels.points_cpu'

Do you have any idea what is causing this?

**Comment by WwZzz** [comment]
I solved the same problem by `pip install torch-point3d`. It automatically downgrades the version of torch-points-kernels to 0.6.10 from 0.7.0, and the issue disappears.
