### ISSUE TITLE
I can‘t install this module successfully，what is the process？

### ISSUE THREAD

**Issue by GeoSur** [torch-points3d/torch-points-kernels#86]
ERROR: Command errored out with exit status 1: /opt/anaconda3/envs/randla/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7c/d0wzvfk159bb8lrgpr_52jl80000gn/T/pip-install-4j8cxrgv/torch-points-kernels_c8978416228f42a7a560a4c21dea52eb/setup.py'"'"'; __file__='"'"'/private/var/folders/7c/d0wzvfk159bb8lrgpr_52jl80000gn/T/pip-install-4j8cxrgv/torch-points-kernels_c8978416228f42a7a560a4c21dea52eb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/7c/d0wzvfk159bb8lrgpr_52jl80000gn/T/pip-record-pjr563e1/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/envs/randla/include/python3.7m/torch-points-kernels Check the logs for full command output.

**Comment by kimdn** [comment]
I encountered the same error in my centos after
`pip install torch-points-kernels`

**Comment by GeoSur** [comment]
> I encountered the same error in my centos after
> `pip install torch-points-kernels`

what device do you use？i found that may because my device without a GPU

**Comment by kimdn** [comment]
> > I encountered the same error in my centos after
> > `pip install torch-points-kernels`
> 
> what device do you use？i found that may because my device without a GPU

I used both
CentOS Linux release 7.8.2003 (Core))
and
CentOS Linux release 7.9.2009 (Core))

**Comment by GeoSur** [comment]
> > > I encountered the same error in my centos after
> > > `pip install torch-points-kernels`
> > 
> > 
> > what device do you use？i found that may because my device without a GPU
> 
> I used both CentOS Linux release 7.8.2003 (Core)) and CentOS Linux release 7.9.2009 (Core))

GPU may solve the problem
