### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_points_kernels.points_cuda'

### ISSUE THREAD

**Issue by Jaychouxq** [torch-points3d/torch-points-kernels#91]
ModuleNotFoundError: No module named 'torch_points_kernels.points_cuda'

**Comment by Stakhan** [comment]
Hi @Jaychouxq,

I think you need to be a bit more specific here. Could you provide the installation steps you followed?

**Comment by CCInc** [comment]
@Jaychouxq usually this is an indication that there was an error compiling the cuda kernel. Please include a log of installation:

`pip install torch-points-kernels -v`
